const {
  Resource,
  ResourceBooking,
  ResourceUsage,
  ResourceMaintenance,
  ResourceRecommendation,
  ResourceAllocationLog
} = require('../models');

async function seedResources() {
  const existingCount = await Resource.count();
  if (existingCount > 0) {
    console.log(`[CAMPUS AI] Resources already seeded (${existingCount} resources found).`);
    return;
  }

  console.log('[CAMPUS AI] Seeding comprehensive Smart Resource Optimization catalog...');

  // 1. Create Core Resources
  const resourcesData = [
    // --- ACADEMIC SPACES ---
    {
      code: 'LAB-B3-01',
      name: 'Computer Lab 1',
      type: 'Computer Laboratory',
      category: 'Academic Space',
      building: 'Block B',
      floor: 2,
      capacity: 60,
      department: 'Computer Science',
      status: 'Available',
      utilizationStatus: 'OVERLOADED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 94.0,
      capacityUtilization: 91.6,
      averageOccupancy: 55,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 37.6,
      weeklyUnusedHours: 2.4,
      peakUsageWindow: '10:00–13:00',
      lowUsageWindow: '16:00–17:00',
      equipmentSpecs: JSON.stringify(['60 High-End Workstations', 'Gigabit Ethernet', 'Dual Projectors', 'NVIDIA GPU Cluster']),
      responsibleDepartment: 'Computer Science',
      healthScore: 78,
      notes: 'Operating near saturation. High thermal stress reported during afternoon practicals.'
    },
    {
      code: 'LAB-B3-02',
      name: 'Computer Lab 3',
      type: 'Computer Laboratory',
      category: 'Academic Space',
      building: 'Block B',
      floor: 2,
      capacity: 60,
      department: 'Computer Science',
      status: 'Available',
      utilizationStatus: 'UNDERUTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 31.0,
      capacityUtilization: 36.7,
      averageOccupancy: 22,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 12.4,
      weeklyUnusedHours: 27.6,
      peakUsageWindow: '10:00–12:00',
      lowUsageWindow: '14:00–16:00',
      equipmentSpecs: JSON.stringify(['60 Core i7 Workstations', 'Dual Projectors', 'Smart Board', 'Gigabit Switch']),
      responsibleDepartment: 'Computer Science',
      healthScore: 96,
      notes: 'Available for immediate practical redistribution. Consistently free in afternoon sessions.'
    },
    {
      code: 'LAB-B3-03',
      name: 'Computer Lab 2',
      type: 'Computer Laboratory',
      category: 'Academic Space',
      building: 'Block B',
      floor: 2,
      capacity: 40,
      department: 'Computer Science',
      status: 'Available',
      utilizationStatus: 'HIGH UTILIZATION',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 76.0,
      capacityUtilization: 72.5,
      averageOccupancy: 29,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 30.4,
      weeklyUnusedHours: 9.6,
      peakUsageWindow: '09:00–13:00',
      lowUsageWindow: '15:30–17:00',
      equipmentSpecs: JSON.stringify(['40 Intel Workstations', 'Overhead Projector']),
      responsibleDepartment: 'Computer Science',
      healthScore: 88,
      notes: 'Healthy usage level.'
    },
    {
      code: 'LAB-B3-04',
      name: 'Computer Lab 4 (Cloud & AI)',
      type: 'Computer Laboratory',
      category: 'Academic Space',
      building: 'Block B',
      floor: 3,
      capacity: 60,
      department: 'Computer Science',
      status: 'Available',
      utilizationStatus: 'OPTIMALLY UTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 48.0,
      capacityUtilization: 50.0,
      averageOccupancy: 30,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 19.2,
      weeklyUnusedHours: 20.8,
      peakUsageWindow: '11:00–13:00',
      lowUsageWindow: '08:30–10:00',
      equipmentSpecs: JSON.stringify(['60 Linux Terminals', 'Docker Cluster', 'Dual Monitors']),
      responsibleDepartment: 'Computer Science',
      healthScore: 94,
      notes: 'Dedicated to AI/ML research and graduate labs.'
    },
    {
      code: 'CR-B2-04',
      name: 'Classroom B-204',
      type: 'Classroom',
      category: 'Academic Space',
      building: 'Block B',
      floor: 2,
      capacity: 50,
      department: 'Electronics & Communication',
      status: 'Available',
      utilizationStatus: 'OPTIMALLY UTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 38.0,
      capacityUtilization: 42.0,
      averageOccupancy: 21,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 15.2,
      weeklyUnusedHours: 24.8,
      peakUsageWindow: '09:00–11:00',
      lowUsageWindow: '14:00–16:00',
      equipmentSpecs: JSON.stringify(['Interactive Smart Board', '4K Laser Projector', 'Acoustic Sound System']),
      responsibleDepartment: 'Academic Operations',
      healthScore: 92,
      notes: 'Ideal match for 45-student lectures needing smart display facilities.'
    },
    {
      code: 'CR-A1-101',
      name: 'Lecture Hall A-101',
      type: 'Lecture Hall',
      category: 'Academic Space',
      building: 'Block A',
      floor: 1,
      capacity: 120,
      department: 'Mechanical Engineering',
      status: 'Available',
      utilizationStatus: 'HIGH UTILIZATION',
      operatingHours: '08:00–18:00',
      operatingStart: '08:00',
      operatingEnd: '18:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 85.0,
      capacityUtilization: 88.0,
      averageOccupancy: 105,
      weeklyAvailableHours: 50.0,
      weeklyUsedHours: 42.5,
      weeklyUnusedHours: 7.5,
      peakUsageWindow: '09:00–13:00',
      lowUsageWindow: '16:00–18:00',
      equipmentSpecs: JSON.stringify(['Tiered Seating', 'Dual Projectors', 'Wireless Mic System']),
      responsibleDepartment: 'Mechanical Engineering',
      healthScore: 85,
      notes: 'Common first-year foundation lectures.'
    },
    {
      code: 'SEM-C1-01',
      name: 'Seminar Hall 1',
      type: 'Seminar Hall',
      category: 'Academic Space',
      building: 'Block C',
      floor: 1,
      capacity: 180,
      department: 'Management Studies',
      status: 'Booked',
      utilizationStatus: 'OVERLOADED',
      operatingHours: '09:00–18:00',
      operatingStart: '09:00',
      operatingEnd: '18:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 92.0,
      capacityUtilization: 86.0,
      averageOccupancy: 155,
      weeklyAvailableHours: 45.0,
      weeklyUsedHours: 41.4,
      weeklyUnusedHours: 3.6,
      peakUsageWindow: '13:00–17:00',
      lowUsageWindow: '09:00–10:00',
      equipmentSpecs: JSON.stringify(['Stage Lighting', 'Dolby Audio', 'Dual 150-inch Screens', 'Podium mic']),
      responsibleDepartment: 'Campus Events Desk',
      healthScore: 80,
      notes: 'High demand next Wednesday. Reroute overflow to Auditorium B.'
    },
    {
      code: 'AUD-C1-01',
      name: 'University Auditorium B',
      type: 'Auditorium',
      category: 'Facilities',
      building: 'Block C',
      floor: 0,
      capacity: 450,
      department: 'Campus Operations',
      status: 'Available',
      utilizationStatus: 'OPTIMALLY UTILIZED',
      operatingHours: '08:00–20:00',
      operatingStart: '08:00',
      operatingEnd: '20:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 42.0,
      capacityUtilization: 40.0,
      averageOccupancy: 180,
      weeklyAvailableHours: 60.0,
      weeklyUsedHours: 25.2,
      weeklyUnusedHours: 34.8,
      peakUsageWindow: '14:00–18:00',
      lowUsageWindow: '08:00–12:00',
      equipmentSpecs: JSON.stringify(['Full Theatre Acoustics', 'Concert Lighting', 'Broadcast Studio']),
      responsibleDepartment: 'Campus Operations',
      healthScore: 95,
      notes: 'Available for large seminar overflow.'
    },
    {
      code: 'TUT-B2-05',
      name: 'Tutorial Room B-205',
      type: 'Tutorial Room',
      category: 'Academic Space',
      building: 'Block B',
      floor: 2,
      capacity: 30,
      department: 'Mathematics',
      status: 'Available',
      utilizationStatus: 'UNDERUTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 24.0,
      capacityUtilization: 26.0,
      averageOccupancy: 8,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 9.6,
      weeklyUnusedHours: 30.4,
      peakUsageWindow: '11:00–13:00',
      lowUsageWindow: '14:00–17:00',
      equipmentSpecs: JSON.stringify(['Whiteboard Wall', 'Digital Display']),
      responsibleDepartment: 'Mathematics',
      healthScore: 94,
      notes: 'Ideal for small remedial coaching or project team breakouts.'
    },

    // --- EQUIPMENT ---
    {
      code: 'EQ-PRJ-01',
      name: 'High-Lumen Laser Projector B-01',
      type: 'Projector',
      category: 'Equipment',
      building: 'Block B',
      floor: 2,
      capacity: 1,
      department: 'IT Support',
      status: 'Available',
      utilizationStatus: 'HIGH UTILIZATION',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 82.0,
      capacityUtilization: 100.0,
      averageOccupancy: 1,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 32.8,
      weeklyUnusedHours: 7.2,
      peakUsageWindow: '10:00–14:00',
      lowUsageWindow: '16:00–17:00',
      equipmentSpecs: JSON.stringify(['6000 Lumens', 'HDMI Wireless Dongle', 'Ceiling Mount']),
      responsibleDepartment: 'IT Support',
      healthScore: 89,
      notes: 'High demand during department guest lectures.'
    },
    {
      code: 'EQ-SBD-03',
      name: 'Interactive Smart Board C-03',
      type: 'Smart Board',
      category: 'Equipment',
      building: 'Block C',
      floor: 2,
      capacity: 1,
      department: 'Management Studies',
      status: 'Available',
      utilizationStatus: 'OPTIMALLY UTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 45.0,
      capacityUtilization: 100.0,
      averageOccupancy: 1,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 18.0,
      weeklyUnusedHours: 22.0,
      peakUsageWindow: '10:00–12:00',
      lowUsageWindow: '14:00–16:00',
      equipmentSpecs: JSON.stringify(['75-inch 4K Touch', 'Stylus pen set', 'Cloud whiteboard']),
      responsibleDepartment: 'IT Support',
      healthScore: 97,
      notes: 'Excellent condition.'
    },
    {
      code: 'EQ-IOT-12',
      name: 'Embedded IoT Bench Testbed',
      type: 'Lab Equipment',
      category: 'Equipment',
      building: 'Block B',
      floor: 3,
      capacity: 15,
      department: 'Electronics & Communication',
      status: 'Available',
      utilizationStatus: 'UNDERUTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 20.0,
      capacityUtilization: 22.0,
      averageOccupancy: 3,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 8.0,
      weeklyUnusedHours: 32.0,
      peakUsageWindow: '14:00–16:00',
      lowUsageWindow: '08:30–11:00',
      equipmentSpecs: JSON.stringify(['15 Raspberry Pi 4 Kits', 'ESP32 Nodes', 'Digital Oscilloscopes']),
      responsibleDepartment: 'Electronics & Communication',
      healthScore: 98,
      notes: 'Low morning usage. Available for open student lab innovation hours.'
    },

    // --- PEOPLE ---
    {
      code: 'STF-TA-01',
      name: 'Senior Lab Assistant (Linux/Cloud)',
      type: 'Technical Staff',
      category: 'People',
      building: 'Block B',
      floor: 2,
      capacity: 1,
      department: 'Computer Science',
      status: 'Available',
      utilizationStatus: 'HIGH UTILIZATION',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 88.0,
      capacityUtilization: 100.0,
      averageOccupancy: 1,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 35.2,
      weeklyUnusedHours: 4.8,
      peakUsageWindow: '09:30–14:30',
      lowUsageWindow: '16:00–17:00',
      equipmentSpecs: JSON.stringify(['RHCE Certified', 'Kubernetes Administrator']),
      responsibleDepartment: 'Computer Science',
      healthScore: 90,
      notes: 'High allocation across continuous practical sessions.'
    },
    {
      code: 'STF-TA-02',
      name: 'Hardware Technician (Robotics Center)',
      type: 'Technical Staff',
      category: 'People',
      building: 'Block A',
      floor: 1,
      capacity: 1,
      department: 'Mechanical Engineering',
      status: 'Available',
      utilizationStatus: 'UNDERUTILIZED',
      operatingHours: '08:30–17:00',
      operatingStart: '08:30',
      operatingEnd: '17:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 28.0,
      capacityUtilization: 100.0,
      averageOccupancy: 1,
      weeklyAvailableHours: 40.0,
      weeklyUsedHours: 11.2,
      weeklyUnusedHours: 28.8,
      peakUsageWindow: '10:00–12:00',
      lowUsageWindow: '13:00–17:00',
      equipmentSpecs: JSON.stringify(['CAD/CAM Operator', '3D Printer Maintenance']),
      responsibleDepartment: 'Mechanical Engineering',
      healthScore: 98,
      notes: 'Available for interdisciplinary fabrication workshops.'
    },

    // --- FACILITIES ---
    {
      code: 'FAC-LIB-01',
      name: 'Central Library Silent Research Zone',
      type: 'Library Space',
      category: 'Facilities',
      building: 'Block A',
      floor: 3,
      capacity: 150,
      department: 'Library Services',
      status: 'Available',
      utilizationStatus: 'OPTIMALLY UTILIZED',
      operatingHours: '08:00–21:00',
      operatingStart: '08:00',
      operatingEnd: '21:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 68.0,
      capacityUtilization: 71.0,
      averageOccupancy: 106,
      weeklyAvailableHours: 65.0,
      weeklyUsedHours: 44.2,
      weeklyUnusedHours: 20.8,
      peakUsageWindow: '13:00–17:00',
      lowUsageWindow: '08:00–10:00',
      equipmentSpecs: JSON.stringify(['Power outlets per cubicle', 'Wi-Fi 6', 'Noise cancellation panels']),
      responsibleDepartment: 'Library Services',
      healthScore: 95,
      notes: 'Steady examination season usage.'
    },
    {
      code: 'FAC-SP-01',
      name: 'Indoor Badminton Arena',
      type: 'Sports Facility',
      category: 'Facilities',
      building: 'Sports Complex',
      floor: 1,
      capacity: 40,
      department: 'Physical Education',
      status: 'Available',
      utilizationStatus: 'OPTIMALLY UTILIZED',
      operatingHours: '06:00–20:00',
      operatingStart: '06:00',
      operatingEnd: '20:00',
      maintenanceStatus: 'Normal',
      timeUtilization: 55.0,
      capacityUtilization: 50.0,
      averageOccupancy: 20,
      weeklyAvailableHours: 70.0,
      weeklyUsedHours: 38.5,
      weeklyUnusedHours: 31.5,
      peakUsageWindow: '16:00–19:00',
      lowUsageWindow: '10:00–14:00',
      equipmentSpecs: JSON.stringify(['4 BWF Wooden Courts', 'LED Floodlights']),
      responsibleDepartment: 'Physical Education',
      healthScore: 92,
      notes: 'Morning and evening spikes. Open for mid-day student recreational tournaments.'
    }
  ];

  const createdResources = await Resource.bulkCreate(resourcesData);
  const resourceMap = {};
  createdResources.forEach(r => { resourceMap[r.code] = r; });

  // 2. Bookings (Including the master demo booking: CS402 Python Practical on Lab 1)
  const lab1 = resourceMap['LAB-B3-01'];
  const lab3 = resourceMap['LAB-B3-02'];
  const sem1 = resourceMap['SEM-C1-01'];
  const cr204 = resourceMap['CR-B2-04'];

  await ResourceBooking.bulkCreate([
    {
      resourceId: lab1.id,
      bookedBy: 'Dr. Sarah Jenkins',
      department: 'Computer Science',
      purpose: 'CS402 Python Programming Practical',
      dayOfWeek: 'Wednesday',
      date: '2026-10-14',
      startTime: '14:00',
      endTime: '16:00',
      expectedOccupancy: 55,
      actualOccupancy: 55,
      status: 'confirmed'
    },
    {
      resourceId: lab1.id,
      bookedBy: 'Prof. Alan Turing',
      department: 'Computer Science',
      purpose: 'CS301 Data Structures Lab',
      dayOfWeek: 'Wednesday',
      date: '2026-10-14',
      startTime: '10:00',
      endTime: '12:00',
      expectedOccupancy: 58,
      actualOccupancy: 58,
      status: 'confirmed'
    },
    {
      resourceId: lab3.id,
      bookedBy: 'Prof. Grace Hopper',
      department: 'Computer Science',
      purpose: 'CS201 Object Oriented Programming Lab',
      dayOfWeek: 'Wednesday',
      date: '2026-10-14',
      startTime: '10:00',
      endTime: '12:00',
      expectedOccupancy: 25,
      actualOccupancy: 22,
      status: 'confirmed'
    },
    {
      resourceId: sem1.id,
      bookedBy: 'Dr. Lisa Ray',
      department: 'Management Studies',
      purpose: 'National Tech & Innovation Summit 2026',
      dayOfWeek: 'Wednesday',
      date: '2026-10-14',
      startTime: '13:00',
      endTime: '17:00',
      expectedOccupancy: 175,
      actualOccupancy: 175,
      status: 'confirmed'
    },
    {
      resourceId: cr204.id,
      bookedBy: 'Dr. Michael Chang',
      department: 'Electronics',
      purpose: 'EC304 Digital Signal Processing Lecture',
      dayOfWeek: 'Wednesday',
      date: '2026-10-14',
      startTime: '09:00',
      endTime: '11:00',
      expectedOccupancy: 42,
      actualOccupancy: 40,
      status: 'confirmed'
    }
  ]);

  // 3. Maintenance schedules
  await ResourceMaintenance.bulkCreate([
    {
      resourceId: lab3.id,
      maintenanceType: 'Routine OS Patch & Antivirus Def Updates',
      startDate: '2026-10-15',
      startTime: '07:00',
      endDate: '2026-10-15',
      endTime: '08:30',
      status: 'completed',
      description: 'Completed regular firmware and Linux kernel patches across all 60 machines.',
      technician: 'Senior Systems Admin'
    },
    {
      resourceId: sem1.id,
      maintenanceType: 'Acoustic Soundcheck & Projector Bulb Calibration',
      startDate: '2026-10-16',
      startTime: '07:30',
      endDate: '2026-10-16',
      endTime: '09:00',
      status: 'scheduled',
      description: 'Pre-event sound calibration ahead of Friday alumni plenary speech.',
      technician: 'Campus AV Operations'
    }
  ]);

  // 4. Initial AI Recommendations (matching Master Prompt specifications!)
  await ResourceRecommendation.bulkCreate([
    {
      resourceId: lab1.id,
      targetResourceId: lab3.id,
      recommendationType: 'swap',
      title: 'Move CS402 Practical from Overloaded Lab 1 to Underutilized Lab 3',
      problem: 'Computer Lab 1 is operating near full capacity (94% utilization) during afternoon practical sessions, creating hardware fatigue and room congestion.',
      evidence: 'Lab 1 has 94% utilization while Computer Lab 3 operates at only 31% utilization with an open unused window between 14:00 and 16:00 (14.5+ unused hours weekly).',
      impact: 'Redistributing the 55-student class balances network load, improves air conditioning efficiency, and elevates Campus Resource Efficiency from 76 to 84.',
      action: 'Reallocate CS402 Python Programming Practical (Wednesday 2:00 PM–4:00 PM) to Computer Lab 3.',
      expectedImprovement: 'Lab 1: 94% → 78% • Lab 3: 31% → 48% • Campus Efficiency: 76 → 84',
      confidence: 92,
      status: 'pending',
      beforeMetrics: JSON.stringify({ lab1Util: 94, lab3Util: 31, efficiency: 76 }),
      afterMetrics: JSON.stringify({ lab1Util: 78, lab3Util: 48, efficiency: 84 }),
      scoreBreakdown: JSON.stringify([
        { factor: 'Availability', points: 30, note: 'Lab 3 100% free 2-4 PM' },
        { factor: 'Capacity Match', points: 25, note: '60 seats fits 55 students' },
        { factor: 'Low Current Utilization', points: 15, note: 'Recovers unused 31% lab' },
        { factor: 'Equipment Match', points: 15, note: '60 Workstations + Projector' },
        { factor: 'Department Match', points: 10, note: 'Computer Science Department' },
        { factor: 'Location Proximity', points: 5, note: 'Floor 2, Block B' }
      ])
    },
    {
      resourceId: sem1.id,
      targetResourceId: resourceMap['AUD-C1-01'].id,
      recommendationType: 'overload',
      title: 'Reroute Wednesday Afternoon Management Seminar to Auditorium B',
      problem: 'Seminar Hall 1 is at 92% peak utilization next Wednesday with an anticipated attendance surge exceeding room capacity.',
      evidence: 'Historical Wednesday booking frequency is 91% with 175 registered attendees for a 180-capacity space (97.2% density).',
      impact: 'Prevents overflow crowding, provides professional stage recording, and leaves Seminar Hall 1 open for executive board meetings.',
      action: 'Shift plenary session to Auditorium B (Capacity 450).',
      expectedImprovement: 'Eliminates congestion risk • Recovers 4 hours capacity',
      confidence: 88,
      status: 'pending',
      beforeMetrics: JSON.stringify({ sem1Util: 92, audUtil: 42 }),
      afterMetrics: JSON.stringify({ sem1Util: 64, audUtil: 55 })
    },
    {
      resourceId: lab3.id,
      recommendationType: 'underutilization',
      title: 'Schedule Practical Sessions in Lab 3 between 2 PM and 4 PM',
      problem: 'Computer Lab 3 has 27.6 hours of unassigned weekly capacity, with low utilization between 2:00 PM and 4:00 PM.',
      evidence: 'IoT sensor logging shows average student occupancy of only 22 out of 60 seats (36.7% capacity utilization).',
      impact: 'Opportunity to absorb 2 extra practical sessions or open research labs without capital expenditure.',
      action: 'Assign project work, remedial labs, or cross-department coding electives during 14:00–16:00 window.',
      expectedImprovement: '+8 hours weekly recovered capacity',
      confidence: 94,
      status: 'pending'
    }
  ]);

  // 5. Initial Audit Log
  await ResourceAllocationLog.create({
    resourceId: lab3.id,
    previousResourceId: null,
    actionType: 'Resource Registration & Baseline Profiling',
    bookingPurpose: 'System Initialization',
    reason: 'Initial baseline calibration of 16 campus resources into the Smart Resource Optimization Engine.',
    approvedBy: 'system@campusai.edu',
    impactSummary: 'Campus baseline established: 126 tracked resources, 74% target optimal utilization, 76 baseline efficiency index.'
  });

  console.log('[CAMPUS AI] Smart Resource Optimization datasets successfully initialized!');
}

module.exports = seedResources;
